### PR TITLE
add contrast check

### PR DESCRIPTION
**Pull request by Monochromish**

### CODE REVIEW

**Comment by Amaru8** [comment]
I will do some testing, the code looks good. One thing, could you please remove the change in the .gitignore for the lockfile?

**Comment by Amaru8** [comment]
Merging it anyway, will remove later. I know this could go against the hardcode git user's rulebook, _but yolo ig_. Thanks for your contribution! ❤️

**Comment by Amaru8** [comment]
oh nice haha

**Comment by Monochromish** [comment]
Well i removed it anyway. np

**Pull request merged**
